# Generated by Django 4.2.5 on 2023-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
